Pong: vibrator: Fix misleading indentation
Output:
device/nothing/Pong/vibrator/Vibrator.cpp:173:13:
error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
            return 0;
            ^
device/xiaomi/lmi/vibrator/Vibrator.cpp:171:9: note: previous statement is here
        if (playLengthMs != NULL)
        ^
1 error generated.

Signed-off-by: Ghosuto <clash.raja10@gmail.com>